services:
  macvlan-router:
    image: ghcr.io/laugmanuel/macvlan-router:main
    container_name: macvlan-router
    restart: unless-stopped
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      MACVLAN_DOCKER_NETWORK: macvlan
      MACVLAN_BRIDGE_IP: 192.168.0.249/24
      INTERVAL: 5 # in seconds
